#!/bin/bash
#Star User Set-up

# set -x

USER=$1

#~ readonly USER=${USER}
#~ readonly HOME=${HOME}
#~ readonly GROUP=$(id -ng "$USER")

if [ ! -d "/home/${USER}/.config/star" ]; then
	mkdir /home/"${USER}"/.config/star
fi

if [ ! -f "/home/${USER}/.config/star/star-setup" ]; then

    cd /etc/skel
    tar cpzf skel.tar.gz .
    mv skel.tar.gz /home/"${USER}"/skel.tar.gz
    cd /home/"${USER}"
    tar xkpsf skel.tar.gz
    rm skel.tar.gz
    
    if [ -f "/etc/apt/sources.list.d/zz-sources.list" ]; then
        rm -f /etc/apt/sources.list.d/zz-sources.list
    fi
    if [ -f "/home/${USER}/.config/autostart/xfce4-autostart.desktop" ]; then
        sed -i "s/REPLACEME/${USER}/g" /home/"${USER}"/.config/autostart/xfce4-autostart.desktop > /dev/null 2>&1     
    fi
    if [ -f "/home/${USER}/.config/xfce4/xfconf/xfce-perchannel-xml/xfce4-keyboard-shortcuts.xml" ]; then
        sed -i "s/REPLACEME/${USER}/g" /home/"${USER}"/.config/xfce4/xfconf/xfce-perchannel-xml/xfce4-keyboard-shortcuts.xml > /dev/null 2>&1
    fi
    #~ if [ -f "/home/$USER/.mozilla/firefox/cpffssvb.default/prefs.js" ]; then
        #~ sed -i "s/REPLACEME/${USER}/g" /home/$USER/.mozilla/firefox/cpffssvb.default/prefs.js > /dev/null 2>&1
    #~ fi
    if [ -f "/home/${USER}/.config/epiphany/session_state.xml" ]; then
		sed -i "s/REPLACEME/${USER}/g" /home/"${USER}"/.config/epiphany/session_state.xml > /dev/null 2>&1
    fi

    ln -s /usr/share/backgrounds /home/"${USER}"/images/wallpapers/shared

	touch /home/"${USER}"/.config/star/star-setup
    chown -R "${USER}":"${USER}" /home/"${USER}"
    
fi

xdg-user-dirs-update

exit 0
