# Mozilla User Preferences

/* Do not edit this file.
 *
 * If you make changes to this file while the application is running,
 * the changes will be overwritten when the application exits.
 *
 * To make a manual change to preferences, you can visit the URL about:config
 */

user_pref("app.update.lastUpdateTime.addon-background-update-timer", 1401516114);
user_pref("app.update.lastUpdateTime.background-update-timer", 1401516354);
user_pref("app.update.lastUpdateTime.blocklist-background-update-timer", 1401516234);
user_pref("app.update.lastUpdateTime.browser-cleanup-thumbnails", 1401514686);
user_pref("app.update.lastUpdateTime.search-engine-update-timer", 1401515994);
user_pref("browser.cache.disk.capacity", 358400);
user_pref("browser.cache.disk.smart_size.first_run", false);
user_pref("browser.cache.disk.smart_size.use_old_max", false);
user_pref("browser.cache.disk.smart_size_cached_value", 358400);
user_pref("browser.download.panel.firstSessionCompleted", true);
user_pref("browser.migration.version", 13);
user_pref("browser.newtabpage.storageVersion", 1);
user_pref("browser.open.lastDir", "/home/REPLACEME/.local/share/star");
user_pref("browser.pagethumbnails.storage_version", 3);
user_pref("browser.places.importBookmarksHTML", false);
user_pref("browser.places.smartBookmarksVersion", 4);
user_pref("browser.slowStartup.averageTime", 4534);
user_pref("browser.slowStartup.samples", 4);
user_pref("browser.startup.homepage", "file:///home/REPLACEME/.local/share/star/star-info.html");
user_pref("browser.startup.homepage_override.buildID", "20140429145318");
user_pref("browser.startup.homepage_override.mstone", "24.5.0");
user_pref("browser.syncPromoViewsLeftMap", "{\"bookmarks\":2}");
user_pref("browser.tabs.warnOnClose", false);
user_pref("datareporting.healthreport.nextDataSubmissionTime", "1401601086005");
user_pref("datareporting.healthreport.service.firstRun", true);
user_pref("datareporting.policy.firstRunTime", "1401514686005");
user_pref("datareporting.sessions.current.activeTicks", 10);
user_pref("datareporting.sessions.current.clean", true);
user_pref("datareporting.sessions.current.firstPaint", 393);
user_pref("datareporting.sessions.current.main", 11);
user_pref("datareporting.sessions.current.sessionRestored", 418);
user_pref("datareporting.sessions.current.startTime", "1401516766329");
user_pref("datareporting.sessions.current.totalTime", 107);
user_pref("datareporting.sessions.currentIndex", 3);
user_pref("datareporting.sessions.previous.0", "{\"s\":1401514672473,\"a\":18,\"t\":110,\"c\":true,\"m\":73,\"fp\":529,\"sr\":14389}");
user_pref("datareporting.sessions.previous.1", "{\"s\":1401515873511,\"a\":38,\"t\":532,\"c\":true,\"m\":11,\"fp\":545,\"sr\":574}");
user_pref("datareporting.sessions.previous.2", "{\"s\":1401516466793,\"a\":9,\"t\":51,\"c\":true,\"m\":642,\"fp\":2440,\"sr\":2682}");
user_pref("extensions.blocklist.pingCountTotal", 2);
user_pref("extensions.blocklist.pingCountVersion", 2);
user_pref("extensions.bootstrappedAddons", "{}");
user_pref("extensions.databaseSchema", 14);
user_pref("extensions.enabledAddons", "%7B972ce4c6-7e08-4474-a285-3208198ce6fd%7D:24.5.0");
user_pref("extensions.installCache", "[{\"name\":\"app-global\",\"addons\":{\"{972ce4c6-7e08-4474-a285-3208198ce6fd}\":{\"descriptor\":\"/usr/lib/iceweasel/browser/extensions/{972ce4c6-7e08-4474-a285-3208198ce6fd}\",\"mtime\":1401514510000,\"rdfTime\":1398788105000}}}]");
user_pref("extensions.lastAppVersion", "24.5.0");
user_pref("extensions.lastPlatformVersion", "24.5.0");
user_pref("extensions.pendingOperations", false);
user_pref("extensions.shownSelectionUI", true);
user_pref("gecko.buildID", "20140429145318");
user_pref("gecko.mstone", "24.5.0");
user_pref("idle.lastDailyNotification", 1401516223);
user_pref("intl.charsetmenu.browser.cache", "UTF-8");
user_pref("network.cookie.prefsMigrated", true);
user_pref("pdfjs.migrationVersion", 1);
user_pref("pdfjs.previousHandler.alwaysAskBeforeHandling", true);
user_pref("pdfjs.previousHandler.preferredAction", 4);
user_pref("places.database.lastMaintenance", 1401516223);
user_pref("places.history.expiration.transient_current_max_pages", 104858);
user_pref("plugin.disable_full_page_plugin_for_types", "application/pdf");
user_pref("pref.browser.homepage.disable_button.current_page", false);
user_pref("privacy.sanitize.migrateFx3Prefs", true);
user_pref("privacy.sanitize.timeSpan", 0);
user_pref("storage.vacuum.last.index", 0);
user_pref("storage.vacuum.last.places.sqlite", 1401516223);
user_pref("toolkit.startup.last_success", 1401516766);
user_pref("toolkit.telemetry.previousBuildID", "20140429161455");
user_pref("urlclassifier.keyupdatetime.https://sb-ssl.google.com/safebrowsing/newkey", 1404107986);
user_pref("xpinstall.whitelist.add", "");
user_pref("xpinstall.whitelist.add.180", "");
user_pref("xpinstall.whitelist.add.36", "");
