#!/bin/sh

# policykit-1-gnome
/usr/lib/policykit-1-gnome/polkit-gnome-authentication-agent-1 &

# will need to know actual name of process
#pgrep wicd-client &>/dev/null; [ $? = 0 ] && killall wicd-client
# pkill wicd-client
pkill conky
# pkill clipit

# before nitrogen
hsetroot -solid "#000000" & 
# hsetroot -solid "#2E3436" & 

sleep 1
{
#	compton --config ~/.compton.conf &
	(sleep 3 && connman-ui-gtk --tray) &
	# (sleep 2 && cmst -m) &
	# (sleep 3 && wicd-gtk --tray) &
# 	(sleep 3 && volumeicon --tray) &
#	(sleep 3 && clipit) &
	(sleep 3 && conky -c ~/.conkyrc) &
	# nitrogen --restore # & not required can cause race conditions
	# feh --bg-scale $HOME/images/wallpapers/shared/filename.jpg &
	(sleep 6 && diy-welcome --firstrun) &
}

## Enable power management
# xfce4-power-manager &

## Start notifications
dunst &

## Start mixer
# volti &

## Set keyboard settings - 250 ms delay and 25 cps (characters per second) repeat rate.
## Adjust the values according to your preferances.
xset r rate 250 25 &

## Turn on/off system beep
xset b off &

## read xpdf, xterm, uxrvt etc.. config
xrdb -merge ~/.Xresources

