alias up='sudo apt-get update && sudo apt-get dist-upgrade'
alias get='sudo apt-get install'
alias rem='sudo apt-get autoremove'
alias cl='sudo apt-get autoclean'
alias se='apt-cache policy'
alias upg='sudo update-grub'
alias grc='ps aux | grep'
alias re='source ~/.bashrc'
alias cd..='cd ..'
alias md=mkdir
alias sdn='sudo shutdown -h now'
alias prg="sudo apt-get purge"
alias ls='ls -F --color --group-directories-first'
alias l="ls -lha"
alias c='clear'
alias q='exit'
alias s='sudo'
