#!/bin/bash
#diy User Set-up

#set -e

USER=$1

if [ ! -d "/home/$USER/.config/diy" ]; then
	mkdir /home/"${USER}"/.config/diy
fi

if [ ! -f "/home/$USER/.config/diy/diy-setup" ]; then

    cd /etc/skel
    tar cpzf skel.tar.gz .
    mv skel.tar.gz /home/"${USER}"/skel.tar.gz
    cd /home/"${USER}"
    tar xkpsf skel.tar.gz
    rm skel.tar.gz

    if [ -f "/home/$USER/.gtkrc-2.0" ]; then
        rpl -q 'REPLACEME' "${USER}" /home/"${USER}"/.gtkrc-2.0 > /dev/null 2>&1
    fi
    if [ -f "/home/${USER}/.config/epiphany/session_state.xml" ]; then
		sed -i "s/REPLACEME/${USER}/g" /home/"${USER}"/.config/epiphany/session_state.xml > /dev/null 2>&1
    fi

    ln -s /usr/share/backgrounds /home/"${USER}"/images/wallpapers/shared

	touch /home/"${USER}"/.config/diy/diy-setup
    chown -R "${USER}":"${USER}" /home/$USER
fi

xdg-user-dirs-update

exit 0
